config/routes.rb
Kyuyo::Application.routes.draw do
  root :to => 'payslips#new'

  resources :payslips
  get 'payslips/:id/pdf' => 'payslips#pdf',  as: 'payslip_pdf'
  post 'payslips/import' => 'payslips#import',  as: 'payslip_import'

  

end

app/models/payslip.rb
class Payslip < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  attr_accessible :basic_pay, :income_tax, :name, :payslip_date, :transportation_expenses, :work_from, :work_to, :working_days, :working_time
  attr_accessible :allow_1, :allow_2, :allow_3, :allow_4, :allow_5, :outworking_time, :allow_1_label, :allow_2_label, :allow_3_label, :allow_4_label, :allow_5_label, :residents_tax, :health_insurance, :welfare_pension, :unemployment_insurance, :deduction_1_label, :deduction_1, :deduction_2_label, :deduction_2, :deduction_3_label, :deduction_3

  def allowanance_amount
    basic_pay.to_i + transportation_expenses.to_i + allow_1.to_i + allow_2.to_i + allow_3.to_i + allow_4.to_i + allow_5.to_i
  end

  def deduction_amount
    income_tax.to_i + deduction_1.to_i + deduction_2.to_i + deduction_3.to_i + unemployment_insurance.to_i + welfare_pension.to_i + health_insurance.to_i + residents_tax.to_i
  end

  def balance
    allowanance_amount - deduction_amount
  end

  def to_pdf
    reports = ThinReports::Report.new layout: File.join(Rails.root , 'app', 'reports', 'basic')

    reports.start_new_page do |page|
      page.values(self.attributes.select {|k, v| page.item_exists?(k) })
      page.values(allowanance_amount: allowanance_amount, 
                  deduction_amount: deduction_amount, 
                  balance: balance)
    end
    reports.generate
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).map do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      payslip = new
      attributes_hash.each do |key, value|
        next if row[value].nil?
        if row[value].class == Date
          row[value] = row[value].strftime('%Y-%m-%d')
        end
        payslip.send("#{key}=", row[value])
      end
      payslip
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.attributes_hash
    {
        basic_pay: '基本給' ,
        income_tax: '所得税' ,
        name: '氏名' ,
        payslip_date: '発行年月',
        transportation_expenses: '非課税通勤費',
        work_from: '労働開始日',
        work_to: '労働終了日' ,
        working_days: '労働日数' ,
        working_time: '労働時間' ,
        allow_1: '支給額1' ,
        allow_1_label: '支給額1名称' ,
        allow_2: '支給額2' ,
        allow_2_label: '支給額2名称' ,
        allow_3: '支給額3' ,
        allow_3_label: '支給額3名称' ,
        allow_4: '支給額4' ,
        allow_4_label: '支給額4名称' ,
        allow_5: '支給額5' ,
        allow_5_label: '支給額5名称' ,
        deduction_1: '控除額1' ,
        deduction_1_label: '控除額1名称',
        deduction_2: '控除額2' ,
        deduction_2_label: '控除額2名称',
        deduction_3: '控除額3' ,
        deduction_3_label: '控除額3名称',
        health_insurance: '健康保険' ,
        outworking_time: '所定時間外労働',
        residents_tax: '住民税',
        unemployment_insurance: '雇用保険',
        welfare_pension: '厚生年金',
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/payslips_controller.rb
class PayslipsController < ApplicationController

  def pdf
    @payslip = Payslip.find(params[:id])

    send_data @payslip.to_pdf, filename: "payslip_#{@payslip.id}",
      type: 'application/pdf', disposition: 'attachment'
  end

  # GET /payslips/new
  # GET /payslips/new.json
  def new
    @payslip = Payslip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payslip }
    end
  end

  # POST /payslips
  def create
    #保存はしないのでmassasign protectionをoffにする
    @payslip = Payslip.new((params[:payslip] || JSON.parse(params[:payslip_obj])), :without_protection => true)

    respond_to do |format|
      if @payslip.valid?
        send_data @payslip.to_pdf, filename: "payslip_#{@payslip.name}_#{@payslip.payslip_date.strftime('%Y_%m')}",
          type: 'application/pdf', disposition: 'attachment'
        return
      else
        format.html { render action: "new" }
      end
    end
  end

  def import
    @payslips = Payslip.import(params[:file])

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payslips_helper.rb
module PayslipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "給与明細" %></title>
    <meta name="description" content="">
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
        @include zurui-ts-000;
        @include zurui-ts-fff;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>
    <div class="container-narrow">

      <div class="masthead">
      </div>

      <hr>

      <div class="jumbotron">
        <h1>PDF給与明細</h1>
        <p class="lead">PDF給与明細を簡単作成</p>
      </div>

      <hr>

      <div class="row-fluid marketing">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->


      <footer>
        <p>PDF is generated by <%= link_to 'ThinReports.org', 'http://www.thinreports.org/' %></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/payslips/_form.html.erb
<%= form_for(@payslip) do |f| %>
  <% if @payslip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payslip.errors.count, "error") %> prohibited this payslip from being saved:</h2>

      <ul>
      <% @payslip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>必要事項を記入してページ下部のボタンを押せばPDFの給与明細が取得出来ます</p>
  <p><%= link_to 'こんな感じの給与明細PDF', '/sample.pdf' %>が簡単に作れます。</p>
  <div> 
  <table class="table table-bordered" style="margin:0 auto;width: 500px;">
    <tr>
      <th> <%= f.label :payslip_date %></th>
      <td colspan="2"> <%= f.date_select :payslip_date, { discard_day: true, use_month_numbers: true }, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.label :name %></th>
      <td colspan="2"> <%= f.text_field :name %> </td>
    </tr>
    <tr>
      <th> <%= f.label '労働期間' %></th>
      <td colspan="2"> <%= f.date_select :work_from, {default: Date.today.beginning_of_month}, { class: 'input-small' } %> から<br/> <%= f.date_select :work_to, {default: Date.today.end_of_month}, { class: 'input-small' } %> まで </td>
    </tr>
    <tr>
      <th> <%= f.label :working_days %> </th>
      <td colspan="2"> <%= f.number_field :working_days %> </td>
    </tr>
    <tr>
      <th> <%= f.label :working_time %> </th>
      <td colspan="2"> <%= f.text_field :working_time %> </td>
    </tr>
    <tr>
      <th> <%= f.label :outworking_time%> </th>
      <td colspan="2"> <%= f.text_field :outworking_time %> </td>
    </tr>
    <tr>
      <th rowspan="7">支給額</th>
      <th> <%= f.label :basic_pay %> </th>
      <td> <%= f.number_field :basic_pay, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.text_field :allow_1_label, { class: 'input-small' } %> </th>
      <td> <%= f.number_field :allow_1, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.text_field :allow_2_label, { class: 'input-small' } %> </th>
      <td> <%= f.number_field :allow_2, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.text_field :allow_3_label, { class: 'input-small' } %> </th>
      <td> <%= f.number_field :allow_3, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.text_field :allow_4_label, { class: 'input-small' } %> </th>
      <td> <%= f.number_field :allow_4, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.text_field :allow_5_label, { class: 'input-small' } %> </th>
      <td> <%= f.number_field :allow_5, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.label :transportation_expenses %> </th>
      <td> <%= f.number_field :transportation_expenses, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th rowspan="8">控除額</th>
      <th> <%= f.label :income_tax %> </th>
      <td> <%= f.number_field :income_tax, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.label :residents_tax %> </th>
      <td> <%= f.number_field :residents_tax, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.label :health_insurance %> </th>
      <td> <%= f.number_field :health_insurance, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.label :welfare_pension %> </th>
      <td> <%= f.number_field :welfare_pension, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.label :unemployment_insurance %> </th>
      <td> <%= f.number_field :unemployment_insurance, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.text_field :deduction_1_label, { class: 'input-small' } %> </th>
      <td> <%= f.number_field :deduction_1, { class: 'input-small' } %> </td>
    </tr>
    <tr>
      <th> <%= f.text_field :deduction_2_label, { class: 'input-small' } %> </th>
      <td> <%= f.number_field :deduction_2, { class: 'input-small' } %> </td>
      </td> </tr>
    <tr>
      <th> <%= f.text_field :deduction_3_label, { class: 'input-small' } %> </th>
      <td> <%= f.number_field :deduction_3, { class: 'input-small' } %> </td>
    </tr>
  </table>
</div>

  <div style='text-align:center' class="actions">
    <p>※入力されたデータはサーバには保存されません。</p>
    <%= f.submit value: 'PDFをダウンロード', class: 'btn btn-large btn-primary' %>
  </div>
<% end %>

app/views/payslips/_upload.html.erb
<h2>Excelによる給与明細一括作成</h2>
<p>
.xls, .xlsx形式のファイルをアップロードして給与明細を一括作成出来ます。
</p>
<div class='well'>
<%= form_tag payslip_import_path, remote:true, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "アップロード", { class: 'btn submit' } %>
<% end %>
</div>

<h2>アップロードファイル仕様</h2>
<p><%= link_to 'このエクセルテンプレート（sample.xlsx）', '/sample.xlsx' %>を修正して使って下さい。発行年月は表示されるのは年月だけですが日までを入れて下さい（2013/6/1など)</p>

app/views/payslips/import.html.erb
<h1>給与明細一覧</h1>

<table class="table">
  <tr>
    <th>年月</th>
    <th>名前</th>
    <th>労働時間</th>
    <th>基本給</th>
    <th>支給額</th>
    <th>控除額</th>
    <th>差引支給額</th>
    <th></th>
  </tr>

<% @payslips.each do |payslip| %>
  <tr>
    <td><%= payslip.payslip_date %></td>
    <td><%= payslip.name %></td>
    <td><%= payslip.working_time %></td>
    <td><%= payslip.basic_pay %></td>
    <td><%= payslip.allowanance_amount %></td>
    <td><%= payslip.deduction_amount %></td>
    <td><%= payslip.balance %></td>
    <td>

      <%= form_for(payslip) do |f| %>
        <%= hidden_field_tag :type, 'import' %>
        <%= hidden_field_tag :payslip_obj, payslip.to_json %>
        <%= f.submit 'PDFダウンロード' %>
      <% end %>
  </tr>
<% end %>
</table>

app/views/payslips/new.html.erb
<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#new" data-toggle="tab">個別作成</a></li>
  <li><a href="#csv" data-toggle="tab">Excel一括作成</a></li>
  <li><a href="#dev" data-toggle="tab">API・開発者向け</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="new">
    <%= render 'form' %>
  </div>
  <div class="tab-pane" id="csv">
    <%= render 'upload' %>
    <div id="csv-list">
    </div>
  </div>
  <div class="tab-pane" id="dev">
    <h2>API</h2>
    <p>
    個別作成のフォームと同じようにPOSTすれば、PDFが作成出来ます。
    </p>
    <h2>ライセンス・ソースコード</h2>
    <p>
    MITライセンスにて配布しています。<%= link_to 'github toyoshi/kyuyo', 'https://github.com/toyoshi/kyuyo' %>
    </p>
  </div>
</div>